package applicationForm;

import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import mysqlConnect.MysqlConnect;

public class PanelBrand extends javax.swing.JPanel {

    Connection conn = null;         //ເກັບການເຊື່ອມຕໍ່ຖານຂໍ້ມູນ
    PreparedStatement pst = null;    //ກຽມຄໍາສັ່ງ SQL
    ResultSet rs = null;       //ເກັບຜົນໄດ້ຮັບ

    public PanelBrand() {
        initComponents();

        JTableHeader header = jTable1.getTableHeader();
        header.setFont(new Font("Defago Noto Sans", Font.PLAIN, 14));
        header.setOpaque(false);
        header.setBackground(new Color(108, 117, 125));
        header.setForeground(new Color(243, 243, 243));

        //ສະແດງຜົນຢູ່ກາງຖັນ
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        jTable1.getColumnModel().getColumn(0).setCellRenderer(centerRenderer);
        jTable1.getColumnModel().getColumn(1).setCellRenderer(centerRenderer);

        //ເສັ້ນຕາຕະລາງ
        jTable1.setShowGrid(false);
        jTable1.setShowHorizontalLines(true);
        jTable1.setShowVerticalLines(true);
        jTable1.setGridColor(new Color(139, 138, 137));

        txtSearch.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "ຄົ້ນຫາສິນຄ້າ");
        txtSearch.putClientProperty(FlatClientProperties.TEXT_FIELD_TRAILING_ICON, new FlatSVGIcon("image_svg/search_text.svg"));

        btnEdit.setEnabled(false);
        btnDelete.setEnabled(false);

        conn = MysqlConnect.connectDB();
         tableUpdate();
         autoID();
    }

    // ສ້າງເມັດຕອດ ສະແດງຄ່າຂໍ້ມູນໃນ ຕຕລ
    private void tableUpdate() {

        try {
            String sql = "SELECT *FROM brand ORDER BY brand_id DESC";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();

            DefaultTableModel d = (DefaultTableModel) jTable1.getModel();
            jTable1.setRowHeight(30); //ຄວາມສູງແຖວ
            d.setRowCount(0); //ລືບຂໍ້ມູນອອກ ຕຕລ

            int row_number = 0;
            while (rs.next()) {
                d.addRow(new Object[]{
                    ++row_number, 
                    rs.getString("brand_id"),
                    rs.getString("brand_name")

                });

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }

    }
    
    //ສ້າງເມັດທອດສ້າງ id
    private void autoID() {

    try {
        String sql = "SELECT SUBSTRING(MAX(brand_id) , 2, 4) FROM brand";
        pst = conn.prepareStatement(sql);
        rs = pst.executeQuery();
        if (rs.next()) {
        int id = rs.getInt(1);
        txtBrand_id.setText("B" + String.format("%03d", ++id));
        } else {
        txtBrand_id.setText("B001");
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e);
    }

    }
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtBrand_id = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        bynAdd = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        txtBrand_name = new javax.swing.JTextField();
        txtSearch = new javax.swing.JTextField();

        jTable1.setFont(new java.awt.Font("Defago Noto Sans", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ລຳດັບ", "ລະຫັດ", "ຢີຫໍ້ສິນຄ້າ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(150);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(150);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(150);
            jTable1.getColumnModel().getColumn(1).setMaxWidth(150);
        }

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ຈັດການຂໍ້ມູນຍີຫໍ້", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Defago Noto Sans", 0, 18), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Defago Noto Sans", 0, 14)); // NOI18N
        jLabel1.setText("ລະຫັດ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 53, 109, 45));

        txtBrand_id.setEditable(false);
        txtBrand_id.setFont(new java.awt.Font("Defago Noto Sans", 0, 14)); // NOI18N
        jPanel1.add(txtBrand_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 210, -1));

        jLabel2.setFont(new java.awt.Font("Defago Noto Sans", 0, 14)); // NOI18N
        jLabel2.setText("ຊື່ສິນຄ້າ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 109, 45));

        btnCancel.setBackground(new java.awt.Color(204, 0, 51));
        btnCancel.setFont(new java.awt.Font("Defago Noto Sans", 0, 14)); // NOI18N
        btnCancel.setText("ຍົກເລີກ");
        btnCancel.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jPanel1.add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, 70, -1));

        bynAdd.setBackground(new java.awt.Color(255, 0, 102));
        bynAdd.setFont(new java.awt.Font("Defago Noto Sans", 0, 14)); // NOI18N
        bynAdd.setText("ເພີ່ມ");
        bynAdd.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jPanel1.add(bynAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 70, -1));

        btnEdit.setBackground(new java.awt.Color(102, 51, 255));
        btnEdit.setFont(new java.awt.Font("Defago Noto Sans", 0, 14)); // NOI18N
        btnEdit.setText("ແກ້ໄຂ");
        btnEdit.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jPanel1.add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 70, -1));

        btnDelete.setBackground(new java.awt.Color(0, 255, 255));
        btnDelete.setFont(new java.awt.Font("Defago Noto Sans", 0, 14)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(0, 0, 0));
        btnDelete.setText("ລືບ");
        btnDelete.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jPanel1.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 70, -1));

        txtBrand_name.setFont(new java.awt.Font("Defago Noto Sans", 0, 14)); // NOI18N
        jPanel1.add(txtBrand_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 210, -1));

        txtSearch.setFont(new java.awt.Font("Defago Noto Sans", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE))
                .addGap(44, 44, 44))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton bynAdd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtBrand_id;
    private javax.swing.JTextField txtBrand_name;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
